### PR TITLE
Add /Haryana/Faridabad, fix error in index.JSON

### PR DESCRIPTION
**Pull request by devanshuyadav**
Add a location in Faridabad, Haryana
Fix missing ',' error in index.JSON

### CODE REVIEW

**Comment by pabloescoder** [comment]
id:155 is also repeated it should be 158, and your landmark should have id 159, check my PR I have corrected that while adding my landmark

**Comment by devanshuyadav** [comment]
@pabloescoder Okay I'll update that.

**Comment by devanshuyadav** [comment]
@sarnobatadi Pls add empty JSON data with IDs in sequence so it does not result in multiple PRs having same ID.

**Comment by devanshuyadav** [comment]
Resolved the Conflict

**Pull request merged**
